name: Python Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'development'
        type: choice
        options:
        - development
        - testing
        - production

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m virtualenv venv
        source venv/bin/activate
        pip install pytest pip-audit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest tests -v

    - name: Security audit with pip-audit
      run: |
        source venv/bin/activate
        echo "Running pip-audit (informational only, will not fail the build)"
        pip-audit > pip-audit-results.txt || echo "Security vulnerabilities found: outputting to build artifact txt file"
        pip-audit --format json > pip-audit-results.json || echo "Security vulnerabilities found: outputting to build artifact detailed json file"
        
    - name: Upload pip-audit scan results
      uses: actions/upload-artifact@v4
      with:
        name: pip-audit-results
        path: |
          pip-audit-results.txt
          pip-audit-results.json
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: capstone-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'capstone-app:latest'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
        output: 'trivy-results.txt'
        
    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.txt